<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFramework>$(DefaultTargetFramework)-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Desknav.ControlPlane\Desknav.ControlPlane.csproj" />
    <ProjectReference Include="..\Desknav.UI.Core\Desknav.UI.Core.csproj" />
  </ItemGroup>

</Project>
