<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>Desknav.UI.Tests</RootNamespace>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Desknav.ControlPlane\Desknav.ControlPlane.csproj" />
    <ProjectReference Include="..\..\src\Desknav.UI.Core\Desknav.UI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

</Project>
